import { Product, Category } from "@/types";

const IMG = "https://picsum.photos/seed";

export const categories: Category[] = [
  { id: "all", name: "All", slug: "all", image: `${IMG}/all/600/600`, count: 12 },
  { id: "1", name: "Dresses", slug: "dresses", image: `${IMG}/dresses/600/600`, count: 6 },
  { id: "2", name: "Abayas", slug: "abayas", image: `${IMG}/abayas/600/600`, count: 6 },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Floral Summer Dress",
    slug: "floral-summer-dress",
    description: "A beautiful floral print dress perfect for summer days. Made from lightweight, breathable cotton with a flattering A-line silhouette.",
    price: 89.99,
    originalPrice: 129.99,
    images: [`${IMG}/dress1/600/800`, `${IMG}/dress2/600/800`],
    category: "dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "White", hex: "#ffffff" }, { name: "Blue", hex: "#4a90d9" }],
    isSale: true,
    rating: 4.5,
  },
  {
    id: "2",
    name: "Cashmere Blend Dress",
    slug: "cashmere-blend-dress",
    description: "Luxuriously soft cashmere blend dress with a relaxed fit. Perfect for layering in cooler months.",
    price: 149.99,
    images: [`${IMG}/sweater1/600/800`, `${IMG}/sweater2/600/800`],
    category: "dresses",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Cream", hex: "#f5e6d3" }, { name: "Black", hex: "#000000" }, { name: "Grey", hex: "#808080" }],
    isNew: true,
    rating: 4.8,
  },
  {
    id: "3",
    name: "Classic Black Abaya",
    slug: "classic-black-abaya",
    description: "Tailored classic black abaya with a wide leg. Crafted from a sustainable wool blend for a sophisticated look.",
    price: 119.99,
    images: [`${IMG}/trousers1/600/800`, `${IMG}/trousers2/600/800`],
    category: "abayas",
    sizes: ["0", "2", "4", "6", "8", "10"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Navy", hex: "#1a2a3a" }],
    rating: 4.3,
  },
  {
    id: "4",
    name: "Leather Crossbody Bag",
    slug: "leather-crossbody-bag",
    description: "Genuine leather crossbody bag with gold-tone hardware. Features an adjustable strap and multiple interior pockets.",
    price: 199.99,
    originalPrice: 259.99,
    images: [`${IMG}/bag1/600/800`, `${IMG}/bag2/600/800`],
    category: "abayas",
    sizes: ["One Size"],
    colors: [{ name: "Tan", hex: "#c4a265" }, { name: "Black", hex: "#000000" }],
    isSale: true,
    rating: 4.7,
  },
  {
    id: "5",
    name: "Classic White Sneakers",
    slug: "classic-white-sneakers",
    description: "Timeless white leather sneakers with a cushioned sole. Versatile enough for both casual and dressed-up looks.",
    price: 129.99,
    images: [`${IMG}/sneakers1/600/800`, `${IMG}/sneakers2/600/800`],
    category: "abayas",
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    colors: [{ name: "White", hex: "#ffffff" }, { name: "Cream", hex: "#f5e6d3" }],
    rating: 4.6,
  },
  {
    id: "6",
    name: "Silk Maxi Dress",
    slug: "silk-maxi-dress",
    description: "Elegant silk maxi dress with a hidden button placket. Fluid and lightweight for a polished everyday look.",
    price: 109.99,
    images: [`${IMG}/blouse1/600/800`, `${IMG}/blouse2/600/800`],
    category: "dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "White", hex: "#ffffff" }, { name: "Pink", hex: "#e8a0bf" }, { name: "Blue", hex: "#4a90d9" }],
    isNew: true,
    rating: 4.4,
  },
  {
    id: "7",
    name: "Denim Shirt Dress",
    slug: "denim-shirt-dress",
    description: "Classic denim shirt dress with a modern fit. Features gold-tone buttons and chest pockets.",
    price: 139.99,
    images: [`${IMG}/jacket1/600/800`, `${IMG}/jacket2/600/800`],
    category: "dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Light Wash", hex: "#7ba0c4" }, { name: "Dark Wash", hex: "#2c4a6e" }],
    rating: 4.5,
  },
  {
    id: "8",
    name: "Evening Gown",
    slug: "evening-gown",
    description: "Stunning floor-length evening gown with a subtle shimmer. Features a sweetheart neckline and flowing skirt.",
    price: 299.99,
    originalPrice: 399.99,
    images: [`${IMG}/gown1/600/800`, `${IMG}/gown2/600/800`],
    category: "dresses",
    sizes: ["0", "2", "4", "6", "8"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Burgundy", hex: "#800020" }],
    isSale: true,
    isNew: true,
    rating: 4.9,
  },
  {
    id: "9",
    name: "Leather Ankle Boots",
    slug: "leather-ankle-boots",
    description: "Chic leather ankle boots with a block heel. Side zipper for easy on-and-off wear.",
    price: 189.99,
    images: [`${IMG}/boots1/600/800`, `${IMG}/boots2/600/800`],
    category: "abayas",
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Brown", hex: "#654321" }],
    rating: 4.6,
  },
  {
    id: "10",
    name: "Wool Blend Abaya Coat",
    slug: "wool-blend-abaya-coat",
    description: "Tailored wool blend abaya coat with notched lapels. A timeless investment piece for your wardrobe.",
    price: 349.99,
    images: [`${IMG}/coat1/600/800`, `${IMG}/coat2/600/800`],
    category: "abayas",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Camel", hex: "#c4a265" }, { name: "Black", hex: "#000000" }, { name: "Grey", hex: "#808080" }],
    isNew: true,
    rating: 4.7,
  },
  {
    id: "11",
    name: "Wide Leg Abaya Pants",
    slug: "wide-leg-abaya-pants",
    description: "Trendy wide leg pants in premium fabric. High-rise waist with a comfortable relaxed fit through the leg.",
    price: 99.99,
    images: [`${IMG}/jeans1/600/800`, `${IMG}/jeans2/600/800`],
    category: "abayas",
    sizes: ["0", "2", "4", "6", "8", "10", "12"],
    colors: [{ name: "Medium Wash", hex: "#5a7a9a" }, { name: "Black", hex: "#000000" }],
    rating: 4.2,
  },
  {
    id: "12",
    name: "Gold Statement Earrings",
    slug: "gold-statement-earrings",
    description: "14k gold-filled statement earrings with a textured finish. Lightweight and perfect for everyday wear.",
    price: 59.99,
    images: [`${IMG}/earrings1/600/800`, `${IMG}/earrings2/600/800`],
    category: "dresses",
    sizes: ["One Size"],
    colors: [{ name: "Gold", hex: "#d4a837" }],
    rating: 4.8,
  },
];
